version: "3"
services:
    service_name:
        image: chellinki/alpine-magento:alpine3.12-php7.3-nginx-mysql5.6-redis-varnish-ssh-cron-rabbitmq3.7.26-jdk11-elasticsearch7.8.1
        container_name: "magento234"
        restart: always
        networks:
            - web
        tty: true
        labels:
            - traefik.http.routers.service_name-https.rule=Host(`magento.sharaths.com`)
            - traefik.http.routers.service_name-https.tls=true
            - traefik.http.routers.service_name-https.tls.certresolver=le
            - traefik.http.routers.service_name-https.service=service_name-https-service
            - traefik.http.services.service_name-https-service.loadbalancer.server.port=80

            - traefik.http.routers.service_name-rmq.rule=Host(`rmq-magento.sharats.com`)
            - traefik.http.routers.service_name-rmq.tls=true
            - traefik.http.routers.service_name-rmq.tls.certresolver=le
            - traefik.http.routers.service_name-rmq.service=service_name-rmq-service
            - traefik.http.services.service_name-rmq-service.loadbalancer.server.port=15672

            - traefik.http.routers.service_name-es.rule=Host(`es-magento.sharaths.com`)
            - traefik.http.routers.service_name-es.tls=true
            - traefik.http.routers.service_name-es.tls.certresolver=le
            - traefik.http.routers.service_name-es.service=service_name-es-service
            - traefik.http.services.service_name-es-service.loadbalancer.server.port=9200
        volumes:
            - ./html:/var/www/html
            - ./database:/var/lib/mysql
            - ./esdata:/usr/share/elasticsearch/data
networks:
    web:
        external: true
