version: "3"
services:
    service_name:
        image: chellinki/alpine:magento2
        container_name: "magento234"
        restart: always
        networks:
            - web
        tty: true
        labels:
            - traefik.http.routers.service_name.rule=Host(`magento.sharaths.com`)
            - traefik.http.routers.service_name.tls=true
            - traefik.http.routers.service_name.tls.certresolver=le
        volumes:
            - ./html:/var/www/html
networks:
    web:
        external: true
