version: "3"
services:
    service_name:
        image: chellinki/alpine-magento:alpine3.7-php7.1-nginx-mysql5.6-redis-varnish-ssh-cron-rabbitmq3.6.15-jdk8-elasticsearch5.6
        container_name: "magento234"
        restart: always
        networks:
            - web
        tty: true
        labels:
            - traefik.http.routers.service_name.rule=Host(`magento.sharaths.com`)
            - traefik.http.routers.service_name.tls=true
            - traefik.http.routers.service_name.tls.certresolver=le
            - traefik.http.services.service_name.loadbalancer.server.port=80
        volumes:
            - ./html:/var/www/html
            - ./database:/var/lib/mysql
            - ./esdata:/usr/share/elasticsearch/data
networks:
    web:
        external: true
